# Generated by Django 4.0.5 on 2022-06-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('school_name', models.CharField(max_length=100)),
                ('grade_number', models.IntegerField(default=1)),
                ('class_number', models.IntegerField(default=1)),
                ('student_number', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('format_of_writing', models.IntegerField(choices=[(1, 'Free writing'), (2, 'Suggestion'), (3, 'Notice')])),
                ('title', models.CharField(max_length=150)),
                ('post', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_author', to='ServerApi.studentuser')),
                ('post_likes', models.ManyToManyField(blank=True, to='ServerApi.studentuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
