# Generated by Django 4.0.5 on 2022-07-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywriting',
            name='format_of_writing',
            field=models.IntegerField(blank=True, choices=[(1, 'Free writing'), (2, 'Suggestion'), (3, 'Notice')], default=1),
        ),
        migrations.AlterField(
            model_name='communitywriting',
            name='title',
            field=models.CharField(blank=True, default='Unnamed post', max_length=150),
        ),
        migrations.AlterField(
            model_name='communitywriting',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('comment_likes', models.ManyToManyField(blank=True, to='ServerApi.studentuser')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_author', to='ServerApi.studentuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='communitywriting',
            name='comments',
            field=models.ManyToManyField(blank=True, to='ServerApi.commentmodel'),
        ),
    ]
