# Generated by Django 4.0.5 on 2022-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0002_alter_communitywriting_format_of_writing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
