# Generated by Django 4.0.5 on 2022-07-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0003_commentmodel_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='post',
            new_name='comment',
        ),
    ]
