# Generated by Django 4.0.5 on 2022-07-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0004_rename_post_commentmodel_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitywriting',
            old_name='comments',
            new_name='comment_list',
        ),
    ]
